### PR TITLE
Fix fetch response in prepareDataProto.

### PR DESCRIPTION
**Pull request by ibuclaw**
Looks like a logic regression bug.  Before it checked if there were no results after _all_ targets had been looked up.

https://github.com/lomik/go-carbon/blob/a19deb850326715e3f846de6acd83094f7030b8c/carbonserver/carbonserver.go#L1276-L1282

I need a couple days to verify this actually fixes it though. :-)

### CODE REVIEW

**Comment by Civil** [comment]
I think it's still good idea to merge this PR, but I'd like to understand if it actually affects the result?

**Comment by ibuclaw** [comment]
@Civil what I saw was that given i.e: `/render/?target=host.one&target=host.two`.

Currently, if the first target returns no data, then `prepareDataProto` exits early, and ultimately returns nothing.  Swap the targets around and data is returned.

**Comment by ibuclaw** [comment]
In the middle of re-reading this, yes this patch is definitely wrong.  The continue in the loop is fine, the check for `metricsFetched` is ok.  But the `+=` is not what I want, as that is an array that's appended to on each loop.

And I see that is also the case for `metrics`, `memoryUsed` and `valuesFetched` too.  All of that code should be hauled out of the range loop and done immediately after.

**Comment by Civil** [comment]
Ah, right, thanks!

I'll wait for you to confirm that your patch works

**Review by Civil — APPROVED** [review]

**Comment by ibuclaw** [comment]
@Civil - confirmed, this patch works.

**Pull request merged**
