### PR TITLE
rpm: added systemd service

### PR DESCRIPTION
**Pull request by n3gster**
Hi. You may want to change the User/Group in the systemd file. Tested against el7 / centos7

### CODE REVIEW

**Comment by morsik** [comment]
This SPEC don't distringhush between EL6 and EL7 (Makefile neither). Doesn't look correct in case of EL6.

**Comment by n3gster** [comment]
I've fixed this & will submit a new PR soon

**Comment by lomik** [comment]
The spec need to add something like this

```
%if 0%{rhel} >= 7
Requires(post): systemd
Requires(preun): systemd
Requires(postun): systemd
BuildRequires: systemd
%endif
```

...

```
%if 0%{rhel} >= 7
%{__install} -pD -m 644 %{name}.systemd %{buildroot}/usr/lib/systemd/system/%{name}.service
%{__install} -pD -m 644 %{name}.sysconfig %{buildroot}/etc/sysconfig/%{name}
%else
%{__install} -pD -m 755 %{name}.init %{buildroot}/etc/init.d/%{name}
%endif
```

...

```
%post
%if 0%{rhel} >= 7
%systemd_post %{name}.service
%endif

%preun
%if 0%{rhel} >= 7
%systemd_preun %{name}.service
%endif

%postun
%if 0%{rhel} >= 7
%systemd_postun_with_restart %{name}.service
%endif
```

...

```
%if 0%{rhel} >= 7
    /usr/lib/systemd/system/%{name}.service
%else
    /etc/init.d/%{name}
%endif
```

And check out the assembly in centos6 and centos7

**Comment by n3gster** [comment]
My spec has:

%if 0%{?rhel} && 0%{?rhel} <= 6

Requires(post):     chkconfig

Requires(preun):    chkconfig

Requires(postun):   initscripts

%else

BuildRequires:      systemd

Requires(post):     systemd

Requires(preun):    systemd

Requires(postun):   systemd

%endif

...

%if 0%{?fedora}%{?el7}

%{__install} -pD -m 755 %{name}.systemd
%{buildroot}/usr/lib/systemd/system/%{name}.service

%else

%{__install} -pD -m 755 %{name}.init %{buildroot}/etc/init.d/%{name}

%endif

...

I've also relocated the binary to /usr/bin and the conf dir to
/etc/go-carbon

I'll take a look at the packaging guidelines & will test against a centos6
vm

**Pull request closed without merging**
