### PR TITLE
Fix up the /find API for use with pickles

### PR DESCRIPTION
**Pull request by jjneely**
metric_path rather than path
isLeaf rather than is_leaf

### CODE REVIEW

**Comment by jjneely** [comment]
It seems odd that I'm the first to find this.  Which makes me question how many others are using graphite-web to query carbonserver directly?

Looks like the recommended path is to continue to use a local graphite-web and query the carbonlink protocol from go-carbon.

**Comment by azhiltsov** [comment]
originally carbonserver (https://github.com/grobian/carbonserver 
) was a standalone binary and was supposed to run aside of carbon-cache.
I joined the team in 2016 and we did not use a pickle already. 
Graphite-web is supposed to talk pickle to carbonzipper (part of carbonapi currently https://github.com/bookingcom/carbonapi) which will use protobuf in its turn. 

So the full-blown setup will have:
go-carbon
|
carbonzipper - graphite-web
|
 \\_carbonapi

I doubt that anyone is using carbonserver with graphite-web

**Comment by lomik** [comment]
Current version of graphite-web supports both "is_leaf" and "isLeaf": https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/finders/remote.py#L121
"is_leaf" is used for compatibility with old graphite-web versions (0.9.x)

**Comment by lomik** [comment]
I deleted my previous comment because I was wrong. Current version of carbonserver compatible only with new graphite-web. After this fix it should be compatible with graphite-web 0.9.x too

@Civil , how about to merge this?

**Pull request merged**
