### PR TITLE
Migrate to go modules

### PR DESCRIPTION
**Pull request by avereha**
This change should address https://github.com/go-graphite/go-carbon/issues/346 and #345
I ran: 'go mod init; go mod tidy' and removed files used by dep. 
Most changes are in the vendor directory(non go files).

Modules that got updated:

 github.com/golang/protobuf from v1.2.0 o v1.4.2
 go-cmp from v0.2.0 to  v0.4.0 
 golang/x/net  
 golang.org/x/sys
 golang/x/text
If there is any concern about those versions I can try to pin them first in Gopkg.toml. 

I tested on one server in production the new version build using modules.

### CODE REVIEW

**Comment by deniszh** [comment]
I tested that quickly, see no issues. Travis is green also. Any objections to merge? @azhiltsov @bom-d-van

**Comment by bom-d-van** [comment]
Nope, LGTM. Thanks for the migration.

**Comment by azhiltsov** [comment]
Same here @deniszh

**Comment by deniszh** [comment]
Merged. Thanks for migration, @avereha !

**Pull request merged**
