### PR TITLE
Add compression support for receiver/tcp

### PR DESCRIPTION
**Pull request by bom-d-van**
cc @Civil

### CODE REVIEW

**Comment by obfuscurity** [comment]
This option is exposed with `-config-print-default` but doesn't appear to be documented anywhere. I assume the supported values are one of `gzip, zip, zlib, flate` (taken from [here](https://github.com/klauspost/compress#usage))?

**Comment by deniszh** [comment]
@obfuscurity : according to https://github.com/lomik/go-carbon/pull/220/files only `gzip` and `snappy` is supported. Also, please note that is only merged in master and not included in any release yet.

**Comment by obfuscurity** [comment]
Ah right, I missed that. Thanks @deniszh.

**Comment by obfuscurity** [comment]
@deniszh Actually, it would appear that compression support is in v0.13.0.

**Comment by deniszh** [comment]
Ah, right. I misread stuff, sorry.

**Comment by obfuscurity** [comment]
No problem. 😄 ❤️

**Comment by deniszh** [comment]
Not sure which relay supports compression, though. Carbon-c-relay should
support it, but not sure if it’s compatible....

**Pull request merged**
