### PR TITLE
Added max read request duration as a graphite metric.

### PR DESCRIPTION
**Pull request by grzkv**
This adds the metric of maximum read request duraion. The implementation extends already existing mechanics for histograms.

### CODE REVIEW

**Comment by azhiltsov** [comment]
Can this be implemented by config option ?
stats-percentiles = [**100,** 99, 98, 95, 75, 50]

**Review by gksinghjsr — APPROVED** [review]
LGTM

**Comment by grzkv** [comment]
Looks like CodeLingo checker just times out without any error messages. Could someone re-run it please. Looks like I cannot do it.

**Comment by deniszh** [comment]
Is this PR still relevant, @grzkv @azhiltsov ?

**Comment by grzkv** [comment]
@deniszh No. Thanks for the reminder.

**Pull request closed without merging**
