### PR TITLE
Fix deadlock between collector and app.ReloadConfig

### PR DESCRIPTION
**Pull request by redbaron**

### CODE REVIEW

**Comment by lomik** [comment]
missed app.Unlock in 

```
if err = app.configure(); err != nil {
        return err
    }
```

**Comment by redbaron** [comment]
you are right. decided to leave defer in there to protect from errors. worst thing if `collector.Stop()`  panics, then defer will try to unlock already  unlocked lock, generating another panic :)

**Comment by lomik** [comment]
Refactored Collector without app.Lock - https://github.com/lomik/go-carbon/commit/8a780f715bba2f713a7dd75ac264ae8f8f974c06
(untested)

**Comment by redbaron** [comment]
if all modules are safe to .Stat when they are stopped (or while they are being stopped), it looks like it is going to work

**Comment by redbaron** [comment]
there is now an implicit not very obvious hard requirement to call NewCollector(app) on any change of app modules, it wasn't the case before though :(

**Comment by lomik** [comment]
Added warning :) https://github.com/lomik/go-carbon/commit/7bd9da4bd74e8fb56345c990a9c14cd81f417d23

**Pull request closed without merging**
