### PR TITLE
fix(carbonserver): find http/grpc - fix metrics_found metric

### PR DESCRIPTION
**Pull request by timtofan**

### CODE REVIEW

**Review by emadolsky — APPROVED** [review]
Approved. But just as an opinion, I think we might be able to call `listener.populateMetricsFoundStat` even when there is a loop which does something else as well. It's cleaner but might cause less performance but I don't think that's much. So your call.

**Comment by timtofan** [comment]
> Approved. But just as an opinion, I think we might be able to call `listener.populateMetricsFoundStat` even when there is a loop which does something else as well. It's cleaner but might cause less performance but I don't think that's much. So your call.

yes I was thinking about it, guess it shouldn't really affect performance, lemme update

**Comment by timtofan** [comment]
@emadolsky updated

**Review by emadolsky — APPROVED** [review]
Awesome! Thanks.

**Pull request merged**
