### PR TITLE
Add Kafka msgpack support

### PR DESCRIPTION
**Pull request by zerosoul13**
Hello,

When I tried to integrate **carbon-relay-ng** through **Kafka** I found that the format produced by **carbon-relay-ng** is not compatible with **go-carbon**. 

This commit adds support for msgpack format so that, if we (the users) decide to use carbon-relay-ng and Kafka, it works out of the box with **go-carbon**.

Related issues:

- https://github.com/grafana/carbon-relay-ng/issues/281#issuecomment-396477417
- https://github.com/go-graphite/go-carbon/issues/288
- https://github.com/grafana/carbon-relay-ng/issues/484

### CODE REVIEW

**Comment by deniszh** [comment]
That's great addition, thanks, @zerosoul13 !
Could you please update vendor directory using `go mod vendor` ? Thanks!

**Comment by deniszh** [comment]
Great, it's green now. It's simple enough to merge, but I would wait for day, maybe someone else want to review.

**Review by deniszh — APPROVED** [review]

**Comment by bom-d-van** [comment]
hi @zerosoul13 , it seems the new protocol isn't handled in [Kafka.worker](https://github.com/go-graphite/go-carbon/blob/1f5665a0b22832222c97056856e97d112ebf01fd/receiver/kafka/kafka.go#L476-L488)?

**Comment by zerosoul13** [comment]
> hi @zerosoul13 , it seems the new protocol isn't handled in [Kafka.worker](https://github.com/go-graphite/go-carbon/blob/1f5665a0b22832222c97056856e97d112ebf01fd/receiver/kafka/kafka.go#L476-L488)?

The missing line has been added.

**Comment by deniszh** [comment]
LGTM. What do you think, @bom-d-van ?

@zerosoul13 - as far as I understand you didn't test it in prod, but you had similar patch implemented, as you discussed in https://github.com/go-graphite/go-carbon/issues/288#issuecomment-767096353 ?

**Comment by zerosoul13** [comment]
@deniszh I tested this patch on a test environment. I was able to consume from a specific Kafka partition without any issues

**Comment by bom-d-van** [comment]
hi yeah, it lgtm as well. thanks for the addition.

**Pull request merged**
