### PR TITLE
[travis-ci] Add apt-get update and go mod vendor to sync gox installation in Travis

### LINKED ISSUE #358: Fix package build
Current build flow (building on travis-ci -> upload to github assets) is broken for some reason:

https://travis-ci.org/github/go-graphite/go-carbon/builds/707431943

```
sudo apt-get install -y rpm ruby ruby-dev

Reading package lists...

Building dependency tree...

Reading state information...

Package rpm is not available, but is referred to by another package.

This may mean that the package is missing, has been obsoleted, or

is only available from another source

Package ruby-dev is not available, but is referred to by another package.

This may mean that the package is missing, has been obsoleted, or

is only available from another source

E: Package 'rpm' has no installation candidate

E: Package 'ruby-dev' has no installation candidate

The command "sudo apt-get install -y rpm ruby ruby-dev" failed and exited with 100 during .
```

### PR DESCRIPTION
**Pull request by alikhtag**
Update apt repository during `before_deploy` and sync go modules after installing `gox` during build
Should fix #358 , one of maintainers please check it Travis :)

### CODE REVIEW

**Review by deniszh — APPROVED** [review]

**Comment by deniszh** [comment]
Unfortunately, in current setup it's even hard to test that. I'll merge and will try. Thanks!

**Comment by alikhtag** [comment]
I guess I could add that I did a small test in forked repo Travis. But did not do `before_deploy`, did `after_script` to run the same commands instead.
https://travis-ci.org/github/alikhtag/go-carbon/builds/707954966

**Comment by deniszh** [comment]
Ah, cool! Will skip test for now then, can wait for next release.
Thanks!

**Comment by alikhtag** [comment]
Forgot to mention, in my Travis ran, I did not check artifact upload for a release. But files should exist based on commands that ran in `before_deploy` and artifact upload should work.

**Pull request merged**
