### PR TITLE
Implement concurrent filepath.Walk

### PR DESCRIPTION
**Pull request by deniszh**
just properly implemented @KingAir idea from https://github.com/lomik/go-carbon/pull/327
didn't test it properly, though

### CODE REVIEW

**Comment by azhiltsov** [comment]
@deniszh @KingAir 
What are the benefits of using cwalk? Can you share any potential or real test cases? 
Is it always superior? I would expect it compete for resource with actual write/render requests.

Another concern here is https://github.com/iafan/cwalk#differences-from-filepathwalk
@bom-d-van does trigram/trie indexing requires sorted input?

**Comment by bom-d-van** [comment]
> does trigram/trie indexing requires sorted input?

@azhiltsov  It might triggered some edge case issues/bugs. But in theory, both solution should be able to work for unordered input.

----

```
err := cwalk.Walk("/path/to/dir", walkFunc)
```

@deniszh better to be able to turn off/on this feature with a flag? Also, if the walkfunc is called concurrently, then we have some race conditions in the code.

**Comment by deniszh** [comment]
TBH I have no idea. Just saw @KingAir PR and saw him as struggling with vendoring, so, created that. If he have no interest - we can close it.

**Comment by deniszh** [comment]
I think it's not revelant anymore, will close it.

**Pull request closed without merging**
